import { createContext, useContext, useState, ReactNode } from 'react';

// Helper to generate dates relative to today
const today = new Date();
const formatDate = (daysOffset: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

// Mock data for demo mode
export const DEMO_MOCK_DATA = {
  profile: {
    id: 'demo-user-id',
    full_name: 'Demo Kullanıcı',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  accounts: [
    {
      id: 'demo-acc-1',
      user_id: 'demo-user-id',
      name: 'Ana Hesap',
      bank_id: 'bank-1',
      bank_name: 'Ziraat Bankası',
      account_type: 'checking',
      balance: 45250.75,
      currency: 'TRY',
      overdraft_limit: 5000,
      overdraft_interest_rate: 2.5,
      iban: 'TR33 0006 1005 1978 6457 8413 26',
      account_number: '6457841326',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-acc-2',
      user_id: 'demo-user-id',
      name: 'Birikim Hesabı',
      bank_id: 'bank-2',
      bank_name: 'İş Bankası',
      account_type: 'savings',
      balance: 125000.00,
      currency: 'TRY',
      overdraft_limit: 0,
      overdraft_interest_rate: 0,
      iban: 'TR45 0006 4000 0011 2345 6789 00',
      account_number: '1234567890',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-acc-3',
      user_id: 'demo-user-id',
      name: 'Döviz Hesabı',
      bank_id: 'bank-3',
      bank_name: 'Garanti BBVA',
      account_type: 'checking',
      balance: 2500.00,
      currency: 'USD',
      overdraft_limit: 0,
      overdraft_interest_rate: 0,
      iban: 'TR78 0006 2000 3456 7890 1234 56',
      account_number: '3456789012',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  credit_cards: [
    {
      id: 'demo-card-1',
      user_id: 'demo-user-id',
      name: 'Gold Kart',
      bank_id: 'bank-1',
      bank_name: 'Ziraat Bankası',
      last_four_digits: '4521',
      card_limit: 50000,
      balance: 12450.00,
      due_date: 15,
      currency: 'TRY',
      minimum_payment: 1245.00,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-card-2',
      user_id: 'demo-user-id',
      name: 'Platinum Kart',
      bank_id: 'bank-2',
      bank_name: 'İş Bankası',
      last_four_digits: '8734',
      card_limit: 75000,
      balance: 8200.00,
      due_date: 22,
      currency: 'TRY',
      minimum_payment: 820.00,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  fixed_payments: [
    {
      id: 'demo-fp-1',
      user_id: 'demo-user-id',
      name: 'Netflix',
      amount: 99.99,
      category: 'entertainment',
      payment_day: 5,
      currency: 'TRY',
      is_active: true,
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-fp-2',
      user_id: 'demo-user-id',
      name: 'Spotify',
      amount: 59.99,
      category: 'entertainment',
      payment_day: 10,
      currency: 'TRY',
      is_active: true,
      account_id: null,
      card_id: 'demo-card-1',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-fp-3',
      user_id: 'demo-user-id',
      name: 'İnternet',
      amount: 450.00,
      category: 'utilities',
      payment_day: 20,
      currency: 'TRY',
      is_active: true,
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-fp-4',
      user_id: 'demo-user-id',
      name: 'Elektrik Faturası',
      amount: 850.00,
      category: 'utilities',
      payment_day: 25,
      currency: 'TRY',
      is_active: true,
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-fp-5',
      user_id: 'demo-user-id',
      name: 'Kira',
      amount: 12000.00,
      category: 'rent',
      payment_day: 1,
      currency: 'TRY',
      is_active: true,
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-fp-6',
      user_id: 'demo-user-id',
      name: 'Doğalgaz',
      amount: 650.00,
      category: 'utilities',
      payment_day: 18,
      currency: 'TRY',
      is_active: true,
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-fp-7',
      user_id: 'demo-user-id',
      name: 'Spor Salonu',
      amount: 750.00,
      category: 'health',
      payment_day: 8,
      currency: 'TRY',
      is_active: true,
      account_id: null,
      card_id: 'demo-card-2',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  installments: [
    {
      id: 'demo-inst-1',
      user_id: 'demo-user-id',
      name: 'iPhone 15 Pro',
      total_amount: 72000,
      monthly_amount: 6000,
      total_months: 12,
      paid_months: 4,
      start_date: formatDate(-120),
      category: 'electronics',
      currency: 'TRY',
      is_active: true,
      card_id: 'demo-card-1',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-inst-2',
      user_id: 'demo-user-id',
      name: 'Tatil Paketi',
      total_amount: 45000,
      monthly_amount: 7500,
      total_months: 6,
      paid_months: 2,
      start_date: formatDate(-60),
      category: 'travel',
      currency: 'TRY',
      is_active: true,
      card_id: 'demo-card-2',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-inst-3',
      user_id: 'demo-user-id',
      name: 'MacBook Air M3',
      total_amount: 58000,
      monthly_amount: 5800,
      total_months: 10,
      paid_months: 3,
      start_date: formatDate(-90),
      category: 'electronics',
      currency: 'TRY',
      is_active: true,
      card_id: 'demo-card-1',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-inst-4',
      user_id: 'demo-user-id',
      name: 'Mobilya Seti',
      total_amount: 35000,
      monthly_amount: 3500,
      total_months: 10,
      paid_months: 6,
      start_date: formatDate(-180),
      category: 'shopping',
      currency: 'TRY',
      is_active: true,
      card_id: 'demo-card-2',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  loans: [
    {
      id: 'demo-loan-1',
      user_id: 'demo-user-id',
      name: 'Konut Kredisi',
      loan_type: 'housing',
      total_amount: 2500000,
      remaining_amount: 2150000,
      monthly_payment: 28500,
      total_months: 120,
      paid_months: 14,
      payment_day: 5,
      interest_rate: 2.49,
      start_date: formatDate(-420),
      end_date: formatDate(3180),
      currency: 'TRY',
      is_active: true,
      bank_id: 'bank-1',
      bank_name: 'Ziraat Bankası',
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-loan-2',
      user_id: 'demo-user-id',
      name: 'Araç Kredisi',
      loan_type: 'vehicle',
      total_amount: 450000,
      remaining_amount: 320000,
      monthly_payment: 12800,
      total_months: 48,
      paid_months: 10,
      payment_day: 12,
      interest_rate: 3.15,
      start_date: formatDate(-300),
      end_date: formatDate(1140),
      currency: 'TRY',
      is_active: true,
      bank_id: 'bank-2',
      bank_name: 'İş Bankası',
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-loan-3',
      user_id: 'demo-user-id',
      name: 'İhtiyaç Kredisi',
      loan_type: 'personal',
      total_amount: 80000,
      remaining_amount: 48000,
      monthly_payment: 4500,
      total_months: 24,
      paid_months: 8,
      payment_day: 20,
      interest_rate: 4.25,
      start_date: formatDate(-240),
      end_date: formatDate(480),
      currency: 'TRY',
      is_active: true,
      bank_id: 'bank-3',
      bank_name: 'Garanti BBVA',
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-loan-4',
      user_id: 'demo-user-id',
      name: 'Eğitim Kredisi - Yüksek Lisans',
      loan_type: 'education',
      total_amount: 120000,
      remaining_amount: 90000,
      monthly_payment: 3750,
      total_months: 36,
      paid_months: 8,
      payment_day: 15,
      interest_rate: 1.89,
      start_date: formatDate(-240),
      end_date: formatDate(840),
      currency: 'TRY',
      is_active: true,
      bank_id: 'bank-4',
      bank_name: 'Halkbank',
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-loan-5',
      user_id: 'demo-user-id',
      name: 'Motosiklet Kredisi',
      loan_type: 'vehicle',
      total_amount: 85000,
      remaining_amount: 21250,
      monthly_payment: 5312,
      total_months: 18,
      paid_months: 12,
      payment_day: 8,
      interest_rate: 3.45,
      start_date: formatDate(-360),
      end_date: formatDate(180),
      currency: 'TRY',
      is_active: true,
      bank_id: 'bank-5',
      bank_name: 'Yapı Kredi',
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-loan-6',
      user_id: 'demo-user-id',
      name: 'Tadilat Kredisi',
      loan_type: 'personal',
      total_amount: 50000,
      remaining_amount: 0,
      monthly_payment: 4545,
      total_months: 12,
      paid_months: 12,
      payment_day: 25,
      interest_rate: 3.99,
      start_date: formatDate(-365),
      end_date: formatDate(-5),
      currency: 'TRY',
      is_active: false,
      bank_id: 'bank-6',
      bank_name: 'Akbank',
      account_id: 'demo-acc-1',
      card_id: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  transactions: [
    {
      id: 'demo-tx-1',
      user_id: 'demo-user-id',
      amount: 28500,
      transaction_type: 'income',
      category: 'salary',
      description: 'Maaş - Aralık 2024',
      transaction_date: formatDate(-1),
      account_id: 'demo-acc-1',
      card_id: null,
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-2',
      user_id: 'demo-user-id',
      amount: 1250.00,
      transaction_type: 'expense',
      category: 'food',
      description: 'Market Alışverişi - Migros',
      transaction_date: formatDate(-2),
      account_id: null,
      card_id: 'demo-card-1',
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-3',
      user_id: 'demo-user-id',
      amount: 350.00,
      transaction_type: 'expense',
      category: 'transport',
      description: 'Benzin - Shell',
      transaction_date: formatDate(-3),
      account_id: 'demo-acc-1',
      card_id: null,
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-4',
      user_id: 'demo-user-id',
      amount: 2500.00,
      transaction_type: 'expense',
      category: 'shopping',
      description: 'Kışlık Giyim',
      transaction_date: formatDate(-4),
      account_id: null,
      card_id: 'demo-card-2',
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-5',
      user_id: 'demo-user-id',
      amount: 450.00,
      transaction_type: 'expense',
      category: 'entertainment',
      description: 'Sinema ve Yemek',
      transaction_date: formatDate(-5),
      account_id: null,
      card_id: 'demo-card-1',
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-6',
      user_id: 'demo-user-id',
      amount: 5000.00,
      transaction_type: 'income',
      category: 'investment',
      description: 'Yatırım Getirisi',
      transaction_date: formatDate(-7),
      account_id: 'demo-acc-2',
      card_id: null,
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-7',
      user_id: 'demo-user-id',
      amount: 12000.00,
      transaction_type: 'expense',
      category: 'rent',
      description: 'Kira Ödemesi - Aralık',
      transaction_date: formatDate(-10),
      account_id: 'demo-acc-1',
      card_id: null,
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-8',
      user_id: 'demo-user-id',
      amount: 180.00,
      transaction_type: 'expense',
      category: 'food',
      description: 'Restoran - Akşam Yemeği',
      transaction_date: formatDate(-6),
      account_id: null,
      card_id: 'demo-card-1',
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-9',
      user_id: 'demo-user-id',
      amount: 3500.00,
      transaction_type: 'expense',
      category: 'health',
      description: 'Diş Tedavisi',
      transaction_date: formatDate(-8),
      account_id: null,
      card_id: 'demo-card-2',
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-10',
      user_id: 'demo-user-id',
      amount: 850.00,
      transaction_type: 'expense',
      category: 'utilities',
      description: 'Elektrik Faturası',
      transaction_date: formatDate(-12),
      account_id: 'demo-acc-1',
      card_id: null,
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-11',
      user_id: 'demo-user-id',
      amount: 2200.00,
      transaction_type: 'income',
      category: 'freelance',
      description: 'Freelance Proje Ödemesi',
      transaction_date: formatDate(-14),
      account_id: 'demo-acc-1',
      card_id: null,
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-tx-12',
      user_id: 'demo-user-id',
      amount: 650.00,
      transaction_type: 'expense',
      category: 'education',
      description: 'Online Kurs - Udemy',
      transaction_date: formatDate(-15),
      account_id: null,
      card_id: 'demo-card-1',
      currency: 'TRY',
      receipt_image_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  savings_goals: [
    {
      id: 'demo-sg-1',
      user_id: 'demo-user-id',
      name: 'Araba Fonu',
      target_amount: 500000,
      current_amount: 125000,
      category: 'vehicle',
      deadline: formatDate(365),
      is_completed: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-sg-2',
      user_id: 'demo-user-id',
      name: 'Acil Durum Fonu',
      target_amount: 100000,
      current_amount: 85000,
      category: 'emergency',
      deadline: formatDate(180),
      is_completed: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-sg-3',
      user_id: 'demo-user-id',
      name: 'Tatil Fonu',
      target_amount: 50000,
      current_amount: 32000,
      category: 'travel',
      deadline: formatDate(120),
      is_completed: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  budget_limits: [
    {
      id: 'demo-bl-1',
      user_id: 'demo-user-id',
      category: 'food',
      monthly_limit: 5000,
      alert_threshold: 80,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-bl-2',
      user_id: 'demo-user-id',
      category: 'entertainment',
      monthly_limit: 2000,
      alert_threshold: 80,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-bl-3',
      user_id: 'demo-user-id',
      category: 'transport',
      monthly_limit: 1500,
      alert_threshold: 75,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-bl-4',
      user_id: 'demo-user-id',
      category: 'shopping',
      monthly_limit: 4000,
      alert_threshold: 80,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-bl-5',
      user_id: 'demo-user-id',
      category: 'utilities',
      monthly_limit: 3500,
      alert_threshold: 90,
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  crypto_holdings: [
    {
      id: 'demo-crypto-1',
      user_id: 'demo-user-id',
      symbol: 'BTC',
      name: 'Bitcoin',
      quantity: 0.15,
      purchase_price: 42500,
      purchase_currency: 'USD',
      exchange: 'Binance',
      notes: 'Uzun vadeli yatırım',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-crypto-2',
      user_id: 'demo-user-id',
      symbol: 'ETH',
      name: 'Ethereum',
      quantity: 2.5,
      purchase_price: 2200,
      purchase_currency: 'USD',
      exchange: 'Binance',
      notes: 'DeFi yatırımı',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-crypto-3',
      user_id: 'demo-user-id',
      symbol: 'SOL',
      name: 'Solana',
      quantity: 25,
      purchase_price: 85,
      purchase_currency: 'USD',
      exchange: 'Binance',
      notes: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  currency_holdings: [
    {
      id: 'demo-curr-1',
      user_id: 'demo-user-id',
      asset_type: 'currency',
      asset_code: 'USD',
      asset_name: 'Amerikan Doları',
      quantity: 5000,
      purchase_price: 32.50,
      purchase_date: formatDate(-30),
      notes: 'Döviz yatırımı',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-curr-2',
      user_id: 'demo-user-id',
      asset_type: 'currency',
      asset_code: 'EUR',
      asset_name: 'Euro',
      quantity: 2000,
      purchase_price: 35.20,
      purchase_date: formatDate(-45),
      notes: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-curr-3',
      user_id: 'demo-user-id',
      asset_type: 'gold',
      asset_code: 'XAU',
      asset_name: 'Gram Altın',
      quantity: 50,
      purchase_price: 2850,
      purchase_date: formatDate(-60),
      notes: 'Güvenli liman yatırımı',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  notifications: [
    {
      id: 'demo-notif-1',
      user_id: 'demo-user-id',
      title: 'Ödeme Hatırlatması',
      message: 'Netflix aboneliğinizin ödeme tarihi 3 gün sonra.',
      notification_type: 'payment_reminder',
      is_read: false,
      priority: 'medium',
      related_entity_type: 'fixed_payment',
      related_entity_id: 'demo-fp-1',
      action_url: '/fixed-payments',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-notif-2',
      user_id: 'demo-user-id',
      title: 'Bütçe Uyarısı',
      message: 'Yemek kategorisinde bütçenizin %80\'ine ulaştınız.',
      notification_type: 'budget_alert',
      is_read: false,
      priority: 'high',
      related_entity_type: 'budget_limit',
      related_entity_id: 'demo-bl-1',
      action_url: '/reports',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-notif-3',
      user_id: 'demo-user-id',
      title: 'Taksit Ödemesi',
      message: 'iPhone 15 Pro taksitiniz 5 gün içinde ödenecek.',
      notification_type: 'installment_reminder',
      is_read: true,
      priority: 'medium',
      related_entity_type: 'installment',
      related_entity_id: 'demo-inst-1',
      action_url: '/installments',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-notif-4',
      user_id: 'demo-user-id',
      title: 'Kredi Ödemesi',
      message: 'Konut kredisi taksitiniz yarın ödenecek.',
      notification_type: 'loan_reminder',
      is_read: false,
      priority: 'high',
      related_entity_type: 'loan',
      related_entity_id: 'demo-loan-1',
      action_url: '/loans',
      created_at: new Date().toISOString(),
    },
  ],
  receipt_items: [
    {
      id: 'demo-ri-1',
      user_id: 'demo-user-id',
      transaction_id: 'demo-tx-2',
      name: 'Süt 1L',
      quantity: 2,
      unit_price: 45.00,
      total_price: 90.00,
      category: 'food',
      brand: 'Sütaş',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-ri-2',
      user_id: 'demo-user-id',
      transaction_id: 'demo-tx-2',
      name: 'Ekmek',
      quantity: 3,
      unit_price: 15.00,
      total_price: 45.00,
      category: 'food',
      brand: 'Uno',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-ri-3',
      user_id: 'demo-user-id',
      transaction_id: 'demo-tx-2',
      name: 'Peynir 500g',
      quantity: 1,
      unit_price: 180.00,
      total_price: 180.00,
      category: 'food',
      brand: 'Pınar',
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-ri-4',
      user_id: 'demo-user-id',
      transaction_id: 'demo-tx-2',
      name: 'Meyve Suyu 1L',
      quantity: 4,
      unit_price: 55.00,
      total_price: 220.00,
      category: 'food',
      brand: 'Cappy',
      created_at: new Date().toISOString(),
    },
  ],
  payment_records: [
    {
      id: 'demo-pr-1',
      user_id: 'demo-user-id',
      fixed_payment_id: 'demo-fp-1',
      payment_month: formatDate(-30).substring(0, 7),
      amount: 99.99,
      paid_at: formatDate(-25),
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-pr-2',
      user_id: 'demo-user-id',
      fixed_payment_id: 'demo-fp-5',
      payment_month: formatDate(-30).substring(0, 7),
      amount: 12000.00,
      paid_at: formatDate(-29),
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-pr-3',
      user_id: 'demo-user-id',
      fixed_payment_id: 'demo-fp-3',
      payment_month: formatDate(0).substring(0, 7),
      amount: 450.00,
      paid_at: formatDate(-5),
      created_at: new Date().toISOString(),
    },
    {
      id: 'demo-pr-4',
      user_id: 'demo-user-id',
      fixed_payment_id: 'demo-fp-4',
      payment_month: formatDate(0).substring(0, 7),
      amount: 850.00,
      paid_at: formatDate(-3),
      created_at: new Date().toISOString(),
    },
  ],
  family_group: {
    id: 'demo-family-1',
    name: 'Demo Ailesi',
    created_by: 'demo-user-id',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  family_members: [
    {
      id: 'demo-fm-1',
      family_id: 'demo-family-1',
      user_id: 'demo-user-id',
      role: 'owner',
      joined_at: new Date().toISOString(),
      profile: {
        full_name: 'Demo Kullanıcı',
      },
    },
    {
      id: 'demo-fm-2',
      family_id: 'demo-family-1',
      user_id: 'demo-user-2',
      role: 'member',
      joined_at: new Date().toISOString(),
      profile: {
        full_name: 'Ayşe Yılmaz',
      },
    },
    {
      id: 'demo-fm-3',
      family_id: 'demo-family-1',
      user_id: 'demo-user-3',
      role: 'member',
      joined_at: new Date().toISOString(),
      profile: {
        full_name: 'Mehmet Demir',
      },
    },
  ],
  family_spending: [
    {
      user_id: 'demo-user-id',
      name: 'Demo Kullanıcı',
      total: 18500,
    },
    {
      user_id: 'demo-user-2',
      name: 'Ayşe Yılmaz',
      total: 12300,
    },
    {
      user_id: 'demo-user-3',
      name: 'Mehmet Demir',
      total: 8750,
    },
  ],
  email_preferences: {
    id: 'demo-ep-1',
    user_id: 'demo-user-id',
    email: 'demo@budgetapp.com',
    frequency: 'weekly' as const,
    is_active: true,
    preferred_hour: 9,
    preferred_minute: 0,
    preferred_day: 1,
    last_sent_at: formatDate(-7),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  push_preferences: {
    id: 'demo-push-1',
    user_id: 'demo-user-id',
    enabled: true,
    payment_reminders: true,
    budget_alerts: true,
    achievement_alerts: true,
    subscription_endpoint: null,
    subscription_keys: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  user_badges: [
    {
      id: 'demo-ub-1',
      user_id: 'demo-user-id',
      badge_id: 'first-transaction',
      progress: 100,
      earned_at: formatDate(-60),
    },
    {
      id: 'demo-ub-2',
      user_id: 'demo-user-id',
      badge_id: 'budget-master',
      progress: 100,
      earned_at: formatDate(-30),
    },
    {
      id: 'demo-ub-3',
      user_id: 'demo-user-id',
      badge_id: 'savings-starter',
      progress: 75,
      earned_at: null,
    },
  ],
  badge_definitions: [
    {
      id: 'first-transaction',
      name: 'İlk Adım',
      description: 'İlk işleminizi oluşturdunuz',
      icon: 'Zap',
      category: 'transactions',
      requirement_type: 'count',
      requirement_value: 1,
      created_at: new Date().toISOString(),
    },
    {
      id: 'budget-master',
      name: 'Bütçe Ustası',
      description: 'Bir ay boyunca bütçe limitlerini aşmadınız',
      icon: 'Target',
      category: 'budget',
      requirement_type: 'streak',
      requirement_value: 30,
      created_at: new Date().toISOString(),
    },
    {
      id: 'savings-starter',
      name: 'Birikim Başlangıcı',
      description: 'Tasarruf hedefinizin %75\'ine ulaştınız',
      icon: 'PiggyBank',
      category: 'savings',
      requirement_type: 'percentage',
      requirement_value: 75,
      created_at: new Date().toISOString(),
    },
    {
      id: 'payment-streak',
      name: 'Ödeme Şampiyonu',
      description: '10 ardışık ödemeyi zamanında yaptınız',
      icon: 'Trophy',
      category: 'payments',
      requirement_type: 'streak',
      requirement_value: 10,
      created_at: new Date().toISOString(),
    },
  ],
};

interface DemoContextType {
  isDemoMode: boolean;
  startDemo: () => void;
  endDemo: () => void;
  demoData: typeof DEMO_MOCK_DATA;
}

const DemoContext = createContext<DemoContextType | undefined>(undefined);

export function DemoProvider({ children }: { children: ReactNode }) {
  const [isDemoMode, setIsDemoMode] = useState(() => {
    return localStorage.getItem('demo_mode') === 'true';
  });

  const startDemo = () => {
    localStorage.setItem('demo_mode', 'true');
    setIsDemoMode(true);
  };

  const endDemo = () => {
    localStorage.removeItem('demo_mode');
    setIsDemoMode(false);
  };

  return (
    <DemoContext.Provider value={{ isDemoMode, startDemo, endDemo, demoData: DEMO_MOCK_DATA }}>
      {children}
    </DemoContext.Provider>
  );
}

export function useDemo() {
  const context = useContext(DemoContext);
  if (context === undefined) {
    throw new Error('useDemo must be used within a DemoProvider');
  }
  return context;
}
