import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface ResendEmailResponse {
  id: string;
}

// Multi-language translations
const translations: Record<string, Record<string, string>> = {
  tr: {
    dailyReport: 'Günlük Finansal Raporunuz',
    weeklyReport: 'Haftalık Finansal Raporunuz',
    monthlyReport: 'Aylık Finansal Raporunuz',
    testReport: 'Test - Finansal Rapor',
    daily: 'Günlük',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    manual: 'Manuel',
    hello: 'Merhaba',
    financialSummary: 'işte finansal durumunuzun detaylı özeti:',
    totalBalance: 'Toplam Bakiye',
    cardDebt: 'Kart Borcu',
    thisMonthIncome: 'Bu Ay Gelir',
    thisMonthExpense: 'Bu Ay Gider',
    last7DaysChart: 'Son 7 Gün Harcama Grafiği',
    categoryDistribution: 'Kategori Dağılımı',
    spendingTrend: 'Harcama Trendi',
    comparedToLastMonth: 'Geçen aya göre harcamalarınız',
    increased: 'arttı',
    decreased: 'azaldı',
    lastMonth: 'Geçen ay',
    topCategories: 'En Yüksek Harcama Kategorileri',
    budgetStatus: 'Bütçe Durumu',
    savingsGoals: 'Tasarruf Hedefleri',
    current: 'Mevcut',
    target: 'Hedef',
    monthlyObligations: 'Aylık Yükümlülükler',
    fixedPayments: 'Sabit Ödemeler',
    installments: 'Taksitler',
    total: 'Toplam',
    last7DaysTransactions: 'Son 7 Gün İşlemler',
    andMore: 've işlem daha',
    netStatus: 'Net Durumunuz',
    assetsMinusDebts: 'Varlıklar - Borçlar',
    autoGenerated: 'Bu rapor otomatik olarak oluşturulmuştur.',
    changePreferences: 'E-posta tercihlerinizi dashboard\'tan değiştirebilirsiniz.',
    date: 'Tarih',
    description: 'Açıklama',
    category: 'Kategori',
    amount: 'Tutar',
    user: 'Kullanıcı',
  },
  en: {
    dailyReport: 'Your Daily Financial Report',
    weeklyReport: 'Your Weekly Financial Report',
    monthlyReport: 'Your Monthly Financial Report',
    testReport: 'Test - Financial Report',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    manual: 'Manual',
    hello: 'Hello',
    financialSummary: 'here is a detailed summary of your financial status:',
    totalBalance: 'Total Balance',
    cardDebt: 'Card Debt',
    thisMonthIncome: 'This Month Income',
    thisMonthExpense: 'This Month Expense',
    last7DaysChart: 'Last 7 Days Spending Chart',
    categoryDistribution: 'Category Distribution',
    spendingTrend: 'Spending Trend',
    comparedToLastMonth: 'Compared to last month, your spending has',
    increased: 'increased',
    decreased: 'decreased',
    lastMonth: 'Last month',
    topCategories: 'Top Spending Categories',
    budgetStatus: 'Budget Status',
    savingsGoals: 'Savings Goals',
    current: 'Current',
    target: 'Target',
    monthlyObligations: 'Monthly Obligations',
    fixedPayments: 'Fixed Payments',
    installments: 'Installments',
    total: 'Total',
    last7DaysTransactions: 'Last 7 Days Transactions',
    andMore: 'more transactions',
    netStatus: 'Your Net Status',
    assetsMinusDebts: 'Assets - Debts',
    autoGenerated: 'This report was automatically generated.',
    changePreferences: 'You can change your email preferences from the dashboard.',
    date: 'Date',
    description: 'Description',
    category: 'Category',
    amount: 'Amount',
    user: 'User',
  },
  de: {
    dailyReport: 'Ihr täglicher Finanzbericht',
    weeklyReport: 'Ihr wöchentlicher Finanzbericht',
    monthlyReport: 'Ihr monatlicher Finanzbericht',
    testReport: 'Test - Finanzbericht',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    manual: 'Manuell',
    hello: 'Hallo',
    financialSummary: 'hier ist eine detaillierte Zusammenfassung Ihrer Finanzlage:',
    totalBalance: 'Gesamtsaldo',
    cardDebt: 'Kartenschuld',
    thisMonthIncome: 'Einnahmen diesen Monat',
    thisMonthExpense: 'Ausgaben diesen Monat',
    last7DaysChart: 'Ausgaben der letzten 7 Tage',
    categoryDistribution: 'Kategorieverteilung',
    spendingTrend: 'Ausgabentrend',
    comparedToLastMonth: 'Im Vergleich zum letzten Monat sind Ihre Ausgaben',
    increased: 'gestiegen',
    decreased: 'gesunken',
    lastMonth: 'Letzter Monat',
    topCategories: 'Top-Ausgabenkategorien',
    budgetStatus: 'Budgetstatus',
    savingsGoals: 'Sparziele',
    current: 'Aktuell',
    target: 'Ziel',
    monthlyObligations: 'Monatliche Verpflichtungen',
    fixedPayments: 'Fixkosten',
    installments: 'Ratenzahlungen',
    total: 'Gesamt',
    last7DaysTransactions: 'Transaktionen der letzten 7 Tage',
    andMore: 'weitere Transaktionen',
    netStatus: 'Ihr Nettostatus',
    assetsMinusDebts: 'Vermögen - Schulden',
    autoGenerated: 'Dieser Bericht wurde automatisch erstellt.',
    changePreferences: 'Sie können Ihre E-Mail-Einstellungen im Dashboard ändern.',
    date: 'Datum',
    description: 'Beschreibung',
    category: 'Kategorie',
    amount: 'Betrag',
    user: 'Benutzer',
  }
};

const getT = (lang: string) => (key: string) => translations[lang]?.[key] || translations['en'][key] || key;

const getLocale = (lang: string) => {
  switch (lang) {
    case 'tr': return 'tr-TR';
    case 'de': return 'de-DE';
    default: return 'en-US';
  }
};

const getCurrencySymbol = (lang: string) => {
  switch (lang) {
    case 'tr': return '₺';
    case 'de': return '€';
    default: return '$';
  }
};

async function sendEmail(to: string, subject: string, html: string): Promise<ResendEmailResponse> {
  console.log(`Sending email to ${to} with subject: ${subject}`);
  
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${RESEND_API_KEY}`,
    },
    body: JSON.stringify({
      from: "BudgetApp <noreply@budgetapp.site>",
      to: [to],
      subject,
      html,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    console.error(`Resend API error: ${error}`);
    throw new Error(`Resend API error: ${error}`);
  }

  return response.json();
}

const formatCurrency = (amount: number, lang: string = 'tr') => {
  const locale = getLocale(lang);
  const symbol = getCurrencySymbol(lang);
  return `${symbol}${amount.toLocaleString(locale, { minimumFractionDigits: 2 })}`;
};

const getProgressBarHtml = (percentage: number, color: string = '#667eea') => {
  const cappedPercentage = Math.min(100, Math.max(0, percentage));
  return `
    <div style="background: #e5e7eb; border-radius: 10px; height: 8px; width: 100%; overflow: hidden;">
      <div style="background: ${color}; height: 100%; width: ${cappedPercentage}%; border-radius: 10px;"></div>
    </div>
  `;
};

const getCategoryEmoji = (category: string) => {
  const emojiMap: Record<string, string> = {
    'Maaş': '💰', 'Salary': '💰', 'Gehalt': '💰',
    'Kira': '🏠', 'Rent': '🏠', 'Miete': '🏠',
    'Market': '🛒', 'Grocery': '🛒', 'Lebensmittel': '🛒',
    'Faturalar': '📄', 'Bills': '📄', 'Rechnungen': '📄',
    'Ulaşım': '🚗', 'Transportation': '🚗', 'Transport': '🚗',
    'Eğlence': '🎬', 'Entertainment': '🎬', 'Unterhaltung': '🎬',
    'Sağlık': '🏥', 'Health': '🏥', 'Gesundheit': '🏥',
    'Giyim': '👕', 'Clothing': '👕', 'Kleidung': '👕',
    'Yemek': '🍽️', 'Food': '🍽️', 'Essen': '🍽️',
    'Diğer': '📦', 'Other': '📦', 'Sonstiges': '📦',
  };
  return emojiMap[category] || '📦';
};

// Generate SVG bar chart for daily spending (last 7 days)
const generateDailySpendingChart = (dailyData: { date: string; amount: number }[], lang: string = 'tr') => {
  const locale = getLocale(lang);
  const maxAmount = Math.max(...dailyData.map(d => d.amount), 1);
  const barWidth = 60;
  const chartHeight = 120;
  const chartWidth = dailyData.length * (barWidth + 10);
  const symbol = getCurrencySymbol(lang);
  
  const bars = dailyData.map((d, i) => {
    const barHeight = (d.amount / maxAmount) * 80;
    const x = i * (barWidth + 10) + 5;
    const y = chartHeight - barHeight - 25;
    const dayName = new Date(d.date).toLocaleDateString(locale, { weekday: 'short' });
    
    return `
      <g>
        <rect x="${x}" y="${y}" width="${barWidth}" height="${barHeight}" fill="url(#barGradient)" rx="4"/>
        <text x="${x + barWidth/2}" y="${chartHeight - 8}" text-anchor="middle" font-size="10" fill="#666">${dayName}</text>
        <text x="${x + barWidth/2}" y="${y - 5}" text-anchor="middle" font-size="9" fill="#333" font-weight="bold">${symbol}${d.amount.toLocaleString(locale)}</text>
      </g>
    `;
  }).join('');

  return `
    <svg width="100%" height="${chartHeight + 10}" viewBox="0 0 ${chartWidth} ${chartHeight + 10}" style="max-width: 100%;">
      <defs>
        <linearGradient id="barGradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color:#667eea"/>
          <stop offset="100%" style="stop-color:#764ba2"/>
        </linearGradient>
      </defs>
      ${bars}
    </svg>
  `;
};

// Generate SVG pie chart for category spending
const generateCategoryPieChart = (categories: [string, number][], lang: string = 'tr') => {
  if (categories.length === 0) return '';
  
  const total = categories.reduce((sum, [, amount]) => sum + amount, 0);
  const colors = ['#667eea', '#764ba2', '#f093fb', '#f5576c', '#4facfe', '#00f2fe', '#43e97b'];
  const size = 140;
  const center = size / 2;
  const radius = 55;
  const symbol = getCurrencySymbol(lang);
  
  let currentAngle = -90;
  const slices = categories.slice(0, 5).map(([category, amount], i) => {
    const percentage = (amount / total) * 100;
    const angle = (percentage / 100) * 360;
    const startAngle = currentAngle;
    const endAngle = currentAngle + angle;
    currentAngle = endAngle;
    
    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;
    
    const x1 = center + radius * Math.cos(startRad);
    const y1 = center + radius * Math.sin(startRad);
    const x2 = center + radius * Math.cos(endRad);
    const y2 = center + radius * Math.sin(endRad);
    
    const largeArc = angle > 180 ? 1 : 0;
    
    return `<path d="M ${center} ${center} L ${x1} ${y1} A ${radius} ${radius} 0 ${largeArc} 1 ${x2} ${y2} Z" fill="${colors[i % colors.length]}"/>`;
  }).join('');

  const legend = categories.slice(0, 5).map(([category, amount], i) => {
    const percentage = ((amount / total) * 100).toFixed(0);
    return `
      <tr>
        <td style="padding: 4px 8px;">
          <span style="display: inline-block; width: 12px; height: 12px; background: ${colors[i % colors.length]}; border-radius: 2px; margin-right: 6px;"></span>
          ${getCategoryEmoji(category)} ${category}
        </td>
        <td style="padding: 4px 8px; text-align: right; font-weight: bold;">%${percentage}</td>
      </tr>
    `;
  }).join('');

  return `
    <div style="display: flex; align-items: center; gap: 20px; flex-wrap: wrap; justify-content: center;">
      <svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
        ${slices}
        <circle cx="${center}" cy="${center}" r="30" fill="white"/>
        <text x="${center}" y="${center + 4}" text-anchor="middle" font-size="12" font-weight="bold" fill="#333">${symbol}${(total/1000).toFixed(0)}K</text>
      </svg>
      <table style="font-size: 12px; color: #333;">${legend}</table>
    </div>
  `;
};

async function generateReportForUser(supabase: any, targetUserId: string, frequency: string, lang: string = 'tr') {
  const t = getT(lang);
  const locale = getLocale(lang);
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const startOfLastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const startOf3MonthsAgo = new Date(now.getFullYear(), now.getMonth() - 2, 1);
  const last7Days = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  // Fetch all user data
  const [
    { data: accounts },
    { data: cards },
    { data: transactions },
    { data: fixedPayments },
    { data: installments },
    { data: profile },
    { data: budgetLimits },
    { data: savingsGoals }
  ] = await Promise.all([
    supabase.from('accounts').select('*').eq('user_id', targetUserId),
    supabase.from('credit_cards').select('*').eq('user_id', targetUserId),
    supabase.from('transactions').select('*').eq('user_id', targetUserId).gte('transaction_date', startOf3MonthsAgo.toISOString()).order('transaction_date', { ascending: false }),
    supabase.from('fixed_payments').select('*').eq('user_id', targetUserId).eq('is_active', true),
    supabase.from('installments').select('*').eq('user_id', targetUserId).eq('is_active', true),
    supabase.from('profiles').select('full_name').eq('id', targetUserId).single(),
    supabase.from('budget_limits').select('*').eq('user_id', targetUserId).eq('is_active', true),
    supabase.from('savings_goals').select('*').eq('user_id', targetUserId).eq('is_completed', false)
  ]);

  // Calculate totals
  const totalBalance = accounts?.reduce((sum: number, acc: any) => sum + Number(acc.balance), 0) || 0;
  const totalCardDebt = cards?.reduce((sum: number, card: any) => sum + Number(card.balance), 0) || 0;
  const totalFixedPayments = fixedPayments?.reduce((sum: number, fp: any) => sum + Number(fp.amount), 0) || 0;
  const totalInstallments = installments?.reduce((sum: number, inst: any) => sum + Number(inst.monthly_amount), 0) || 0;

  // Monthly transactions analysis
  const monthlyTransactions = transactions?.filter((t: any) => new Date(t.transaction_date) >= startOfMonth) || [];
  const lastMonthTransactions = transactions?.filter((t: any) => {
    const date = new Date(t.transaction_date);
    return date >= startOfLastMonth && date < startOfMonth;
  }) || [];

  // Last 7 days transactions
  const last7DaysTransactions = transactions?.filter((t: any) => new Date(t.transaction_date) >= last7Days) || [];
  
  // Daily spending for chart (last 7 days)
  const dailySpending: Record<string, number> = {};
  for (let i = 6; i >= 0; i--) {
    const date = new Date(now.getTime() - i * 24 * 60 * 60 * 1000);
    const dateStr = date.toISOString().split('T')[0];
    dailySpending[dateStr] = 0;
  }
  last7DaysTransactions.filter((t: any) => t.transaction_type === 'expense').forEach((t: any) => {
    const dateStr = t.transaction_date.split('T')[0];
    if (dailySpending.hasOwnProperty(dateStr)) {
      dailySpending[dateStr] += Number(t.amount);
    }
  });
  const dailySpendingData = Object.entries(dailySpending).map(([date, amount]) => ({ date, amount }));

  const monthlyIncome = monthlyTransactions.filter((t: any) => t.transaction_type === 'income').reduce((sum: number, t: any) => sum + Number(t.amount), 0);
  const monthlyExpense = monthlyTransactions.filter((t: any) => t.transaction_type === 'expense').reduce((sum: number, t: any) => sum + Number(t.amount), 0);
  const lastMonthExpense = lastMonthTransactions.filter((t: any) => t.transaction_type === 'expense').reduce((sum: number, t: any) => sum + Number(t.amount), 0);

  // Expense change percentage
  const expenseChangePercent = lastMonthExpense > 0 
    ? ((monthlyExpense - lastMonthExpense) / lastMonthExpense * 100).toFixed(1)
    : '0';
  const isExpenseIncreased = monthlyExpense > lastMonthExpense;

  // Top spending categories
  const categorySpending: Record<string, number> = {};
  monthlyTransactions.filter((t: any) => t.transaction_type === 'expense').forEach((t: any) => {
    categorySpending[t.category] = (categorySpending[t.category] || 0) + Number(t.amount);
  });
  const topCategories = Object.entries(categorySpending)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  // Budget limit status
  const budgetStatus = (budgetLimits || []).map((limit: any) => {
    const spent = categorySpending[limit.category] || 0;
    const percentage = (spent / Number(limit.monthly_limit)) * 100;
    return {
      category: limit.category,
      limit: Number(limit.monthly_limit),
      spent,
      percentage: Math.min(100, percentage),
      isExceeded: percentage >= 100,
      isWarning: percentage >= (limit.alert_threshold || 80)
    };
  });

  // Savings goals progress
  const goalsProgress = (savingsGoals || []).map((goal: any) => ({
    name: goal.name,
    target: Number(goal.target_amount),
    current: Number(goal.current_amount),
    percentage: (Number(goal.current_amount) / Number(goal.target_amount)) * 100,
    remaining: Number(goal.target_amount) - Number(goal.current_amount)
  }));

  const userName = profile?.full_name || t('user');
  const reportDate = now.toLocaleDateString(locale, { 
    weekday: 'long', 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  const frequencyText = frequency === 'daily' ? t('daily') : frequency === 'weekly' ? t('weekly') : frequency === 'monthly' ? t('monthly') : t('manual');

  // Build enhanced email HTML
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 0; background-color: #f5f5f5; }
    .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 10px 0 0; opacity: 0.9; font-size: 14px; }
    .content { padding: 25px; }
    .greeting { font-size: 16px; margin-bottom: 20px; color: #333; }
    .summary-grid { display: table; width: 100%; margin-bottom: 25px; }
    .summary-row { display: table-row; }
    .summary-card { display: table-cell; width: 50%; padding: 8px; vertical-align: top; }
    .summary-card-inner { background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center; }
    .summary-card-inner.positive { background: #e8f5e9; }
    .summary-card-inner.negative { background: #ffebee; }
    .summary-card-inner.warning { background: #fff3e0; }
    .summary-card-inner h3 { margin: 0 0 5px; font-size: 12px; color: #666; font-weight: normal; }
    .summary-card-inner p { margin: 0; font-size: 20px; font-weight: bold; }
    .summary-card-inner.positive p { color: #2e7d32; }
    .summary-card-inner.negative p { color: #c62828; }
    .summary-card-inner.warning p { color: #ef6c00; }
    .section { margin-top: 25px; padding-top: 20px; border-top: 1px solid #eee; }
    .section-title { font-size: 16px; color: #333; margin-bottom: 15px; display: flex; align-items: center; gap: 8px; }
    .section-title span { font-size: 20px; }
    .trend-badge { display: inline-block; padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: bold; }
    .trend-up { background: #ffebee; color: #c62828; }
    .trend-down { background: #e8f5e9; color: #2e7d32; }
    .category-row { display: flex; justify-content: space-between; align-items: center; padding: 10px 0; border-bottom: 1px solid #f0f0f0; }
    .category-row:last-child { border-bottom: none; }
    .category-name { display: flex; align-items: center; gap: 8px; font-size: 14px; }
    .category-amount { font-weight: bold; color: #333; }
    .goal-item { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 10px; }
    .goal-header { display: flex; justify-content: space-between; margin-bottom: 8px; }
    .goal-name { font-weight: bold; color: #333; }
    .goal-progress { font-size: 12px; color: #666; }
    .budget-item { padding: 12px 0; border-bottom: 1px solid #f0f0f0; }
    .budget-header { display: flex; justify-content: space-between; margin-bottom: 6px; }
    .budget-exceeded { color: #c62828; }
    .budget-warning { color: #ef6c00; }
    .budget-ok { color: #2e7d32; }
    .obligations-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f0f0f0; }
    .footer { background: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #666; }
    .footer a { color: #667eea; text-decoration: none; }
    .net-status { text-align: center; padding: 20px; background: linear-gradient(135deg, ${(totalBalance - totalCardDebt) >= 0 ? '#e8f5e9' : '#ffebee'} 0%, ${(totalBalance - totalCardDebt) >= 0 ? '#c8e6c9' : '#ffcdd2'} 100%); border-radius: 12px; margin-top: 15px; }
    .net-status h3 { margin: 0 0 8px; font-size: 14px; color: #666; }
    .net-status p { margin: 0; font-size: 28px; font-weight: bold; color: ${(totalBalance - totalCardDebt) >= 0 ? '#2e7d32' : '#c62828'}; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 ${frequencyText} ${frequency === 'daily' ? t('dailyReport').split(' ').slice(1).join(' ') : frequency === 'weekly' ? t('weeklyReport').split(' ').slice(1).join(' ') : t('monthlyReport').split(' ').slice(1).join(' ')}</h1>
      <p>${reportDate}</p>
    </div>
    
    <div class="content">
      <div class="greeting">
        ${t('hello')} <strong>${userName}</strong>, ${t('financialSummary')}
      </div>
      
      <!-- Summary Cards -->
      <div class="summary-grid">
        <div class="summary-row">
          <div class="summary-card">
            <div class="summary-card-inner ${totalBalance >= 0 ? 'positive' : 'negative'}">
              <h3>💰 ${t('totalBalance')}</h3>
              <p>${formatCurrency(totalBalance, lang)}</p>
            </div>
          </div>
          <div class="summary-card">
            <div class="summary-card-inner negative">
              <h3>💳 ${t('cardDebt')}</h3>
              <p>${formatCurrency(totalCardDebt, lang)}</p>
            </div>
          </div>
        </div>
        <div class="summary-row">
          <div class="summary-card">
            <div class="summary-card-inner positive">
              <h3>📈 ${t('thisMonthIncome')}</h3>
              <p>${formatCurrency(monthlyIncome, lang)}</p>
            </div>
          </div>
          <div class="summary-card">
            <div class="summary-card-inner warning">
              <h3>📉 ${t('thisMonthExpense')}</h3>
              <p>${formatCurrency(monthlyExpense, lang)}</p>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Daily Spending Chart -->
      <div class="section">
        <div class="section-title"><span>📊</span> ${t('last7DaysChart')}</div>
        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; overflow-x: auto;">
          ${generateDailySpendingChart(dailySpendingData, lang)}
        </div>
      </div>

      <!-- Category Pie Chart -->
      ${topCategories.length > 0 ? `
      <div class="section">
        <div class="section-title"><span>🥧</span> ${t('categoryDistribution')}</div>
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px;">
          ${generateCategoryPieChart(topCategories, lang)}
        </div>
      </div>
      ` : ''}

      <!-- Spending Trend -->
      <div class="section">
        <div class="section-title">
          <span>📈</span> ${t('spendingTrend')}
          <span class="trend-badge ${isExpenseIncreased ? 'trend-up' : 'trend-down'}">
            ${isExpenseIncreased ? '↑' : '↓'} ${Math.abs(Number(expenseChangePercent))}%
          </span>
        </div>
        <p style="font-size: 14px; color: #666; margin: 0;">
          ${t('comparedToLastMonth')} ${isExpenseIncreased ? t('increased') : t('decreased')}. 
          ${t('lastMonth')}: ${formatCurrency(lastMonthExpense, lang)}
        </p>
      </div>
      
      <!-- Top Categories -->
      ${topCategories.length > 0 ? `
      <div class="section">
        <div class="section-title"><span>🏷️</span> ${t('topCategories')}</div>
        ${topCategories.map(([category, amount]) => `
          <div class="category-row">
            <div class="category-name">
              <span>${getCategoryEmoji(category)}</span>
              ${category}
            </div>
            <span class="category-amount">${formatCurrency(amount, lang)}</span>
          </div>
        `).join('')}
      </div>
      ` : ''}
      
      <!-- Budget Limits -->
      ${budgetStatus.length > 0 ? `
      <div class="section">
        <div class="section-title"><span>🎯</span> ${t('budgetStatus')}</div>
        ${budgetStatus.map((budget: any) => `
          <div class="budget-item">
            <div class="budget-header">
              <span class="${budget.isExceeded ? 'budget-exceeded' : budget.isWarning ? 'budget-warning' : 'budget-ok'}">
                ${getCategoryEmoji(budget.category)} ${budget.category}
              </span>
              <span class="${budget.isExceeded ? 'budget-exceeded' : budget.isWarning ? 'budget-warning' : 'budget-ok'}">
                ${formatCurrency(budget.spent, lang)} / ${formatCurrency(budget.limit, lang)}
              </span>
            </div>
            ${getProgressBarHtml(budget.percentage, budget.isExceeded ? '#c62828' : budget.isWarning ? '#ef6c00' : '#2e7d32')}
          </div>
        `).join('')}
      </div>
      ` : ''}
      
      <!-- Savings Goals -->
      ${goalsProgress.length > 0 ? `
      <div class="section">
        <div class="section-title"><span>🎯</span> ${t('savingsGoals')}</div>
        ${goalsProgress.map((goal: any) => `
          <div class="goal-item">
            <div class="goal-header">
              <span class="goal-name">🎯 ${goal.name}</span>
              <span class="goal-progress">${goal.percentage.toFixed(0)}%</span>
            </div>
            ${getProgressBarHtml(goal.percentage, '#667eea')}
            <div style="display: flex; justify-content: space-between; margin-top: 8px; font-size: 12px; color: #666;">
              <span>${t('current')}: ${formatCurrency(goal.current, lang)}</span>
              <span>${t('target')}: ${formatCurrency(goal.target, lang)}</span>
            </div>
          </div>
        `).join('')}
      </div>
      ` : ''}
      
      <!-- Monthly Obligations -->
      <div class="section">
        <div class="section-title"><span>📋</span> ${t('monthlyObligations')}</div>
        <div class="obligations-row">
          <span>🏦 ${t('fixedPayments')}</span>
          <strong>${formatCurrency(totalFixedPayments, lang)}</strong>
        </div>
        <div class="obligations-row">
          <span>💳 ${t('installments')}</span>
          <strong>${formatCurrency(totalInstallments, lang)}</strong>
        </div>
        <div class="obligations-row" style="border-bottom: none; font-size: 16px;">
          <span><strong>${t('total')}</strong></span>
          <strong style="color: #667eea;">${formatCurrency(totalFixedPayments + totalInstallments, lang)}</strong>
        </div>
      </div>

      <!-- Last 7 Days Transactions -->
      ${last7DaysTransactions.length > 0 ? `
      <div class="section">
        <div class="section-title"><span>📝</span> ${t('last7DaysTransactions')}</div>
        <table style="width: 100%; font-size: 12px; border-collapse: collapse;">
          <thead>
            <tr style="background: #f8f9fa;">
              <th style="padding: 10px; text-align: left; border-bottom: 2px solid #e5e7eb;">${t('date')}</th>
              <th style="padding: 10px; text-align: left; border-bottom: 2px solid #e5e7eb;">${t('description')}</th>
              <th style="padding: 10px; text-align: left; border-bottom: 2px solid #e5e7eb;">${t('category')}</th>
              <th style="padding: 10px; text-align: right; border-bottom: 2px solid #e5e7eb;">${t('amount')}</th>
            </tr>
          </thead>
          <tbody>
            ${last7DaysTransactions.slice(0, 15).map((txn: any) => `
              <tr>
                <td style="padding: 8px 10px; border-bottom: 1px solid #f0f0f0;">
                  ${new Date(txn.transaction_date).toLocaleDateString(locale, { day: 'numeric', month: 'short' })}
                </td>
                <td style="padding: 8px 10px; border-bottom: 1px solid #f0f0f0;">
                  ${txn.description || '-'}
                </td>
                <td style="padding: 8px 10px; border-bottom: 1px solid #f0f0f0;">
                  ${getCategoryEmoji(txn.category)} ${txn.category}
                </td>
                <td style="padding: 8px 10px; border-bottom: 1px solid #f0f0f0; text-align: right; font-weight: bold; color: ${txn.transaction_type === 'income' ? '#2e7d32' : '#c62828'};">
                  ${txn.transaction_type === 'income' ? '+' : '-'}${formatCurrency(Number(txn.amount), lang)}
                </td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        ${last7DaysTransactions.length > 15 ? `
          <p style="text-align: center; font-size: 12px; color: #666; margin-top: 10px;">
            ... ${last7DaysTransactions.length - 15} ${t('andMore')}
          </p>
        ` : ''}
      </div>
      ` : ''}
      
      <!-- Net Status -->
      <div class="net-status">
        <h3>💡 ${t('netStatus')}</h3>
        <p>${formatCurrency(totalBalance - totalCardDebt, lang)}</p>
        <p style="font-size: 12px; color: #666; margin-top: 8px;">${t('assetsMinusDebts')}</p>
      </div>
    </div>
    
    <div class="footer">
      <p>${t('autoGenerated')}</p>
      <p>${t('changePreferences')}</p>
    </div>
  </div>
</body>
</html>
  `;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    const body = await req.json();
    const { userId, frequency, cron } = body;

    // Handle cron job requests
    if (cron && frequency) {
      console.log(`Processing ${frequency} cron job at ${new Date().toISOString()}`);
      
      // Verify cron authentication - check body secret OR header
      const cronSecret = Deno.env.get('CRON_AUTH_SECRET');
      if (!cronSecret) {
        console.error('CRON_AUTH_SECRET not configured - endpoint is disabled for security');
        return new Response(JSON.stringify({ error: 'Server misconfigured' }), {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      
      // Accept secret from body (cron_secret field) or Authorization header
      const bodySecret = body.cron_secret;
      const authHeader = req.headers.get('Authorization');
      const headerSecret = authHeader?.replace('Bearer ', '');
      const providedSecret = bodySecret || headerSecret;
      
      if (providedSecret !== cronSecret) {
        console.log('Unauthorized cron call attempt');
        return new Response(JSON.stringify({ error: 'Unauthorized' }), {
          status: 401,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      
      const supabase = createClient(supabaseUrl, supabaseServiceKey);
      const now = new Date();
      const currentHour = now.getUTCHours(); // Use UTC for consistency
      const currentDay = now.getUTCDay(); // 0 = Sunday, 1 = Monday, ...
      const currentDayOfMonth = now.getUTCDate(); // 1-31
      
      console.log(`Current UTC time: hour=${currentHour}, dayOfWeek=${currentDay}, dayOfMonth=${currentDayOfMonth}`);
      
      // Build query based on frequency - always filter by preferred_hour
      let query = supabase
        .from("email_preferences")
        .select("*")
        .eq("is_active", true)
        .eq("frequency", frequency)
        .eq("preferred_hour", currentHour);

      // For weekly reports, also check preferred_day (day of week)
      if (frequency === "weekly") {
        query = query.eq("preferred_day", currentDay);
      }
      
      // For monthly reports, also check preferred_day (day of month)
      if (frequency === "monthly") {
        query = query.eq("preferred_day", currentDayOfMonth);
      }

      const { data: preferences, error: prefsError } = await query;

      if (prefsError) {
        console.error("Error fetching email preferences:", prefsError);
        return new Response(
          JSON.stringify({ error: "Failed to fetch preferences" }),
          { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );
      }

      if (!preferences || preferences.length === 0) {
        console.log(`No active ${frequency} email preferences found for hour ${currentHour}${frequency === 'weekly' ? `, day of week ${currentDay}` : ''}${frequency === 'monthly' ? `, day of month ${currentDayOfMonth}` : ''}`);
        return new Response(
          JSON.stringify({ message: "No preferences to process" }),
          { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
        );
      }

      console.log(`Found ${preferences.length} users to send ${frequency} reports`);

      // Send report to each user
      const results = await Promise.allSettled(
        preferences.map(async (pref) => {
          try {
            const userLang = pref.language || 'tr';
            const t = getT(userLang);
            const emailContent = await generateReportForUser(supabase, pref.user_id, frequency, userLang);
            
            const subjectKey = frequency === 'daily' ? 'dailyReport' : frequency === 'weekly' ? 'weeklyReport' : 'monthlyReport';
            const emailResponse = await sendEmail(
              pref.email,
              `📊 ${t(subjectKey)}`,
              emailContent
            );

            // Update last_sent_at
            await supabase
              .from("email_preferences")
              .update({ last_sent_at: new Date().toISOString() })
              .eq("id", pref.id);

            return { success: true, email: pref.email, response: emailResponse };
          } catch (error) {
            console.error(`Error sending to ${pref.email}:`, error);
            return { success: false, email: pref.email, error: String(error) };
          }
        })
      );

      const successCount = results.filter(r => r.status === 'fulfilled' && r.value.success).length;
      console.log(`Successfully sent ${successCount}/${preferences.length} ${frequency} reports`);

      return new Response(
        JSON.stringify({ 
          message: `Sent ${successCount}/${preferences.length} reports`,
          results 
        }),
        { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    // Handle manual/test report requests (requires authentication)
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      console.error("No authorization header provided");
      return new Response(JSON.stringify({ error: 'Unauthorized - No authorization header' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const supabaseAuth = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } }
    });

    const { data: { user }, error: userError } = await supabaseAuth.auth.getUser();
    if (userError || !user) {
      console.error("Authentication failed:", userError?.message || "No user found");
      return new Response(JSON.stringify({ error: 'Unauthorized - Invalid token' }), {
        status: 401,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log(`Authenticated user: ${user.id}`);

    if (userId && userId !== user.id) {
      console.error(`User ${user.id} attempted to access data for user ${userId}`);
      return new Response(JSON.stringify({ error: 'Forbidden - Cannot access other users data' }), {
        status: 403,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const targetUserId = userId || user.id;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    console.log(`Looking for email preferences for user ${targetUserId}`);

    // For manual/test reports, don't require is_active to be true
    const { data: prefs, error: prefsError } = await supabase
      .from('email_preferences')
      .select('user_id, email, language')
      .eq('user_id', targetUserId)
      .maybeSingle();
    
    if (prefsError) {
      console.error("Error fetching preferences:", prefsError);
      return new Response(JSON.stringify({ 
        success: false, 
        error: 'Failed to fetch email preferences' 
      }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // If no preferences found, use user's email from auth
    const targetEmail = prefs?.email || user.email;
    const userLang = prefs?.language || 'tr';
    const t = getT(userLang);
    
    if (!targetEmail) {
      console.error("No email found for user");
      return new Response(JSON.stringify({ 
        success: false, 
        error: 'No email address found for user' 
      }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    console.log(`Will send test report to: ${targetEmail} in language: ${userLang}`);

    console.log(`Preparing enhanced report for user ${targetUserId}`);

    const emailContent = await generateReportForUser(supabase, targetUserId, frequency || 'daily', userLang);
    const emailResponse = await sendEmail(
      targetEmail,
      `📊 ${t('testReport')}`,
      emailContent
    );

    console.log("Email sent successfully:", emailResponse);

    return new Response(JSON.stringify(emailResponse), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-report-email function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
});
